INSERT INTO outbox_messages(id,
                            occurred_at,
                            type,
                            routing_key,
                            payload,
                            headers,
                            status,
                            attempts,
                            next_attempt_at,
                            published_at)
VALUES (@Id,
        @OccurredAt,
        @Type,
        @RoutingKey,
        cast(@PayloadJson as jsonb),
        cast(@HeadersJson as jsonb),
        @Status,
        @Attempts,
        @NextAttemptAt,
        @PublishedAt)