INSERT INTO transactions (id,
                          account_id,
                          counterparty_account_id,
                          amount,
                          currency_code,
                          type,
                          description,
                          timestamp)
VALUES (@Id,
        @AccountId,
        @CounterpartyAccountId,
        @Amount,
        @Currency,
        @Type,
        @Description,
        @Timestamp);